// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgBXsRQL9T3wo3kPbMXjqoZiaRZKZs7p0',
    appId: '1:771222115852:web:5f2d04d5b4d727732e0029',
    messagingSenderId: '771222115852',
    projectId: 'gigi-dialogflow-srvu',
    authDomain: 'gigi-dialogflow-srvu.firebaseapp.com',
    storageBucket: 'gigi-dialogflow-srvu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNeLlrq6RB9X-32lulo4GRrcgQhrcrMJ8',
    appId: '1:771222115852:android:ade91e2144475bdc2e0029',
    messagingSenderId: '771222115852',
    projectId: 'gigi-dialogflow-srvu',
    storageBucket: 'gigi-dialogflow-srvu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjo183s4HgM0jcvdVfVg6_32Dz1xTU670',
    appId: '1:771222115852:ios:d5473bf822524c8a2e0029',
    messagingSenderId: '771222115852',
    projectId: 'gigi-dialogflow-srvu',
    storageBucket: 'gigi-dialogflow-srvu.appspot.com',
    iosClientId: '771222115852-bm8b309cacttqmpcsmd3aurii05t5jje.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjo183s4HgM0jcvdVfVg6_32Dz1xTU670',
    appId: '1:771222115852:ios:16389197b13a92732e0029',
    messagingSenderId: '771222115852',
    projectId: 'gigi-dialogflow-srvu',
    storageBucket: 'gigi-dialogflow-srvu.appspot.com',
    iosClientId: '771222115852-a4j8j26tn3tpsd0a0b9uv5v98vsaitas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignin.RunnerTests',
  );
}
